version: '3'

services:

    django:
        build:
            context: .
            dockerfile: ./docker/product/django/Dockerfile
        command: sh ./docker/product/django/entrypoint.sh
        env_file: ./docker/product/django/.env
        ports:
        - 8001:8001
        volumes:
        - static_volume:/static
        depends_on:
        - postgres
        networks:
        - nginx_network
        - postgres_network

    postgres:
        build:
            context: .
            dockerfile: ./docker/product/postgres/Dockerfile
        env_file: ./docker/product/postgres/.env
        ports:
        - 5432:5432
        volumes:
        - postgres_volume:/pgdata
        networks:
        - postgres_network

    nginx:
        build:
            context: .
            dockerfile: ./docker/product/nginx/Dockerfile
        ports:
        - 3000:80
        volumes:
        - static_volume:/static
        depends_on:
        - django
        networks:
        - nginx_network
        
networks:
    nginx_network:
        driver: bridge
    postgres_network:
        driver: bridge

volumes:
    static_volume:
    postgres_volume:
